//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema; 
    using System.Linq;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int id { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public int pickUpPointId { get; set; }
        public int clientId { get; set; }
        public string pickUpCode { get; set; }
        public int statusId { get; set; }
    
        public virtual User User { get; set; }
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }

        [NotMapped] 
        public string ProductListDescription
        {
            get
            {
                if (OrderProduct == null || !OrderProduct.Any())
                    return "Нет товаров";

                var descriptions = OrderProduct.Select(op =>
                    $"{op.Product.articul} - {op.quantity} шт.").ToArray();
                return string.Join(", ", descriptions);
            }
        }
    }
}
